import { useMemo, useState } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { Check, ExternalLink, LoaderCircle, LockKeyhole, LogOut, Palette, RefreshCw, ShieldCheck, SlidersHorizontal } from 'lucide-react';
import { getGetAccountQueryKey, useDisconnectGoogleAccount, useGetAccount, useHealthCheck, useListCategories } from '@workspace/api-client-react';
import { AppShell, SectionKicker, SkeletonBlock } from '@/components/app-shell';

export default function SettingsPage() {
  const accountQuery = useGetAccount();
  const categoriesQuery = useListCategories();
  const healthQuery = useHealthCheck();
  const disconnect = useDisconnectGoogleAccount();
  const queryClient = useQueryClient();
  const account = accountQuery.data;
  const [enabled, setEnabled] = useState<Record<string, boolean>>({});
  const categories = useMemo(() => categoriesQuery.data ?? [], [categoriesQuery.data]);
  const toggle = (id: string, next: boolean) => setEnabled((current) => ({ ...current, [id]: next }));

  return <AppShell><div className="mx-auto max-w-[980px] animate-enter">
    <div className="mb-9"><SectionKicker>Workspace / settings</SectionKicker><h1 className="text-3xl font-semibold tracking-[-0.055em] sm:text-[40px]">Keep the boundary clear.</h1><p className="mt-3 max-w-xl text-sm leading-relaxed text-muted-foreground">Control what Inbox Classifier can see and how your inbox gets organized. These choices stay local to your account.</p></div>
    <div className="space-y-5">
      <section className="rounded-xl border border-border bg-card p-5 shadow-[0_12px_30px_hsl(var(--foreground)/.035)] sm:p-6" data-testid="card-gmail-connection"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div className="flex gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-[#E7F0F0] text-primary"><ExternalLink className="h-5 w-5" /></div><div><SectionKicker>Gmail connection</SectionKicker><h2 className="text-lg font-semibold">{account?.connected ? 'Gmail is connected' : 'No Gmail account connected'}</h2><p className="mt-1 text-sm text-muted-foreground">{account?.email ?? 'Connect an account to scan your inbox metadata.'}</p></div></div><div className="flex items-center gap-2 rounded-full bg-[#E6F0EC] px-3 py-1.5 text-xs font-semibold text-[#35654E]" data-testid="status-connection">{account?.connected ? <><span className="h-1.5 w-1.5 rounded-full bg-[#5C9B7B]" />Connected</> : 'Disconnected'}</div></div><div className="mt-6 flex flex-wrap gap-2 border-t border-border pt-5"><a href="/api/account/connect" data-testid="button-connect-gmail" className="inline-flex h-10 items-center gap-2 rounded-lg bg-primary px-3.5 text-sm font-semibold text-primary-foreground disabled:opacity-50"><ExternalLink className="h-4 w-4" />{account?.connected ? 'Reconnect Gmail' : 'Connect Gmail'}</a>{account?.connected && <button type="button" onClick={() => disconnect.mutate(undefined, { onSuccess: (nextAccount) => queryClient.setQueryData(getGetAccountQueryKey(), nextAccount) })} disabled={disconnect.isPending} data-testid="button-disconnect-gmail" className="inline-flex h-10 items-center gap-2 rounded-lg border border-border bg-background px-3.5 text-sm font-semibold text-foreground hover:bg-muted disabled:opacity-50"><LogOut className="h-4 w-4" />{disconnect.isPending ? 'Disconnecting…' : 'Disconnect'}</button>}</div></section>

      <section className="rounded-xl border border-border bg-card p-5 shadow-[0_12px_30px_hsl(var(--foreground)/.035)] sm:p-6" data-testid="card-privacy-explanation"><div className="flex gap-4"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-[#F7EBC4] text-[#92752C]"><LockKeyhole className="h-5 w-5" /></div><div><SectionKicker>Privacy model</SectionKicker><h2 className="text-lg font-semibold">Metadata in. Message bodies out.</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">Inbox Classifier uses sender, subject preview, thread IDs, and timing signals to suggest categories. It does not retain message bodies, attachments, or full content. Disconnecting Gmail stops future reads; your aggregate counts remain available.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-lg bg-muted/65 p-3"><ShieldCheck className="h-4 w-4 text-[#5C9B7B]" /><div className="mt-2 text-xs font-semibold">No body storage</div><div className="mt-1 text-[11px] text-muted-foreground">Message content is never saved.</div></div><div className="rounded-lg bg-muted/65 p-3"><SlidersHorizontal className="h-4 w-4 text-primary" /><div className="mt-2 text-xs font-semibold">Your categories</div><div className="mt-1 text-[11px] text-muted-foreground">You decide what fits.</div></div><div className="rounded-lg bg-muted/65 p-3"><RefreshCw className="h-4 w-4 text-[#B9783F]" /><div className="mt-2 text-xs font-semibold">Reversible</div><div className="mt-1 text-[11px] text-muted-foreground">Review before labels apply.</div></div></div></div></div></section>

      <section className="rounded-xl border border-border bg-card shadow-[0_12px_30px_hsl(var(--foreground)/.035)]" data-testid="card-configured-categories"><div className="flex flex-col justify-between gap-2 border-b border-border p-5 sm:flex-row sm:items-center sm:p-6"><div><SectionKicker>Classification system</SectionKicker><h2 className="text-lg font-semibold">Configured categories</h2></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><Palette className="h-3.5 w-3.5" /> {categories.length} active lanes</div></div>{categoriesQuery.isLoading ? <div className="space-y-3 p-5" data-testid="state-settings-loading">{[1, 2, 3].map((item) => <SkeletonBlock key={item} className="h-14" />)}</div> : categories.length === 0 ? <div className="p-6 text-sm text-muted-foreground" data-testid="state-categories-settings-empty">No categories have been configured yet.</div> : <div className="divide-y divide-border">{categories.map((item) => { const isEnabled = enabled[item.id] ?? true; return <div key={item.id} className="flex items-center justify-between gap-4 px-5 py-4 sm:px-6" data-testid={`setting-category-${item.id}`}><div className="flex items-center gap-3"><span className="h-3 w-3 rounded-full" style={{ backgroundColor: item.color }} /><div><div className="text-sm font-semibold">{item.name}</div><div className="mt-0.5 text-xs text-muted-foreground">{item.count.toLocaleString()} messages · {Math.round((item.share ?? 0) * 100)}% of view</div></div></div><button type="button" role="switch" aria-checked={isEnabled} onClick={() => toggle(item.id, !isEnabled)} data-testid={`button-toggle-category-${item.id}`} className={`relative h-6 w-11 rounded-full transition-colors ${isEnabled ? 'bg-primary' : 'bg-muted'}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-card shadow-sm transition-transform ${isEnabled ? 'translate-x-6' : 'translate-x-1'}`} /> </button></div>; })}</div>}</section>
      <div className="flex items-center justify-between px-1 text-xs text-muted-foreground" data-testid="status-api-health"><span>Service status</span><span className="flex items-center gap-1.5">{healthQuery.isLoading ? <LoaderCircle className="h-3 w-3 animate-spin" /> : <Check className="h-3 w-3 text-[#5C9B7B]" />}{healthQuery.data?.status ?? (healthQuery.isError ? 'Unavailable' : 'Operational')}</span></div>
    </div>
  </div></AppShell>;
}
